### ISSUE TITLE
cli: port from structopt to clap-v3

### ISSUE THREAD

**Issue by lucab** [ostreedev/ostree-rs-ext#373]
For CLI handling we are currently using `structopt`:
https://github.com/ostreedev/ostree-rs-ext/blob/e1975de4eebb861b70a265701a467b67a6e3063a/cli/Cargo.toml#L14

However nowadays we are hitting the ceiling of unmaintained transitive dependencies:
https://github.com/clap-rs/clap/discussions/4172

As suggested in the discussion post, at this point we should move to `clap` v3.

**Comment by cgwalters** [comment]
I'd started a WIP on this in https://github.com/ostreedev/ostree-rs-ext/pull/345

**Comment by lucab** [comment]
Thanks for the reference, I'll take over that PR.
