### ISSUE TITLE
container detection fails inside `docker buildx`

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree-rs-ext#380]
I was playing around with GH actions for container building, it uses `docker buildx` by default and the environment there appears to lack `/.dockerenv`.

Hmmm.  It's a bit tempting to force on setting the `container` environment variable in ostree native containers.

**Comment by vrutkovs** [comment]
I've hit this in github actions in https://github.com/vrutkovs/custom-okd-os and the fix was to add
`ENV container oci` in the dockerfile
