### ISSUE TITLE
Encapsulated OSTree commits should retain timestamp

### ISSUE THREAD

**Issue by jlebon** [ostreedev/ostree-rs-ext#420]
Right now, OSTree containers have:

```
"Created": "0001-01-01T00:00:00Z"
```

IIUC, I think this is because we're not actually setting the `Created` field on [the image configuration](https://github.com/ostreedev/ostree-rs-ext/blob/fa59f819ae1ce5837ada346338a73d56297d757e/lib/src/container/encapsulate.rs#L223).

Should we be setting that to the timestamp of the OSTree commit?

**Comment by cgwalters** [comment]
Hmm, yes, arguably.  That said...I think we should also teach rpm-ostree to probably default to setting a commit timestamp to be the latest timestamp of all input RPMs.  (And for ostree layers, all input layers).

That'd help ensure that generated container images are more reproducible too after we do this.

**Comment by cgwalters** [comment]
https://github.com/ostreedev/ostree-rs-ext/pull/445 is related to this
