### ISSUE TITLE
Our Usecase

### ISSUE THREAD

**Issue by t-moe** [ostreedev/ostree-rs-ext#470]
Hi there,
We have a use case for ostree-rs-ext and I wanted to ask whether this use case is supported, or what is required to make it work.

We have an ostree-booted embedded system that runs some containerized applications (docker compose). Now we're in the process of building an (offline, non-OTA) updater for that.  The updater delivers an OS-Tree repo which contains the new rootfs. The ostree revision is then deployed and the system reboots into the new updated rootfs.

So far we have updated the containers manually (outside of ostree). But as far as I understand it, this project allows to store container images as part of the ostree repo.

Some questions related to that:

- How can import my existing docker images into ostree? The unencapsulate command seems to require that the commit metadata is already part of the image, so I can't use this.
- Am I correct, that after switching to a new ostree revision, I need to run the encapsulate command so that docker is able to run the containers from the updated images? Does this mean that the image data duplicated? (it is stored once as part of the ostree repo and once as the exported image that docker will run). 

Thank you for pointing me into the right direction, on how to advance this use case.

**Comment by RishabhSaini** [comment]
Un-encapsulate is meant to convert an existing ostree-based container image to an ostree deployment. Encapsulate does the opposite. They both are a part of [`rpm-ostree rebase`](https://coreos.github.io/rpm-ostree/container/#rebasing-a-client-system), which helps upgrade your system from current deployment to the one stored in the ostree-based container. These ostree-based container images contain the entire OS update and are different from application based container images.

To import exisiting application based docker images:
As a part of your build process, you could save your docker images as tar files in `/etc/your-containers-repo/` and then load your docker images from there.  
`docker save -o <path for generated tar file> <image name>`
`docker load -i <path to image tar file>`  

To ensure the you always get the updated docker images:
Pull from the remote registry as a part of your ostree deployment build process
`docker pull`
